SAMPLE_DOCTORS = [
    {
        "id": 1,
        "name": "Dr. Priya Sharma",
        "initials": "PS",
        "email": "priya@moodmate.in",
        "password_hash": "pbkdf2:sha256:600000$9icmZPMiTvtrScJQ$5f8406455a762ad776bde40e94f749f1fdd0d75add41980a4bbbb30b576e3c4b",
        "specialization": "Clinical Psychology",
        "experience_years": 8,
        "languages": ["Hindi", "English"],
        "modes": ["Video", "Chat"],
        "price_per_session": 1999,
        "rating": 4.9,
        "reviews_count": 128,
        "badge": "RCI Licensed Clinician",
        "bio": "A CBT-oriented psychologist focused on anxiety, panic, and work stress. Sessions are practical, structured, and paced gently for first-time therapy clients.",
        "license_info": "RCI Licensed Clinical Psychologist (CRR No. A12345)",
        "qualifications": ["MPhil Clinical Psychology (TISS)", "RCI Licensed", "CBT Mastery (Beck Institute)"],
        "approaches": ["CBT", "ACT", "Mindfulness"],
        "focus_areas": ["Anxiety", "Panic", "Stress", "Burnout", "Self-esteem"],
        "best_for": "Adults who want a structured therapist with homework, coping tools, and clear next steps.",
        "first_session": "The first session covers background, current stressors, goals for therapy, and a simple plan for the next one to two weeks.",
        "cancellation_policy": "Reschedule or cancel at least 12 hours in advance. Mutual respect for time is core to our therapy contract.",
        "review_summary": "Clients describe Priya as clear, calm, and practical, especially when they feel overwhelmed or stuck in worry loops.",
        "availability": ["Mon 2 PM", "Wed 10 AM", "Fri 4 PM"],
        "photo_url": "",
        "profile_source": "managed",
    },
    {
        "id": 2,
        "name": "Aaryan Kumar",
        "initials": "AK",
        "email": "aaryan@moodmate.in",
        "password_hash": "pbkdf2:sha256:600000$Tod27kYJY0tLspn8$7b8b081dc6616bf7c7519b3da032e20c8f2dc68679681b27c7fc9e45b9d5d4a5",
        "specialization": "Counseling Psychology",
        "experience_years": 5,
        "languages": ["Hindi", "English"],
        "modes": ["Voice", "Chat"],
        "price_per_session": 599,
        "rating": 4.7,
        "reviews_count": 84,
        "badge": "Accessible care",
        "bio": "Works with students and young professionals around career confusion, relationship stress, and emotional overwhelm.",
        "license_info": "Counseling psychologist sample profile for product demo",
        "qualifications": ["MA Counseling Psychology", "Career counseling certification"],
        "approaches": ["Supportive therapy", "CBT-informed", "Solution-focused"],
        "focus_areas": ["Career stress", "Relationships", "Low confidence", "Life transitions"],
        "best_for": "People who want a warm listener and practical support during change-heavy life phases.",
        "first_session": "The first session maps the main stress pattern, clarifies what support feels useful, and sets one manageable goal before the next conversation.",
        "cancellation_policy": "Sample policy: cancel at least 12 hours before the scheduled start time.",
        "review_summary": "Clients say Aaryan feels non-judgmental and easy to open up to, especially when life feels confusing.",
        "availability": ["Tue 9 AM", "Thu 3 PM", "Sat 11 AM"],
        "photo_url": "",
        "profile_source": "sample",
    },
    {
        "id": 3,
        "name": "Dr. Ankur Verma",
        "initials": "AV",
        "email": "ankur@moodmate.in",
        "password_hash": "pbkdf2:sha256:600000$UfQgLjxA5e6fzZKs$ae77970ed7abe68359de48260e3c655e1488f32df6937e8ee4b20d8ce0783aed",
        "specialization": "Psychiatry",
        "experience_years": 12,
        "languages": ["English", "Hindi"],
        "modes": ["Video"],
        "price_per_session": 999,
        "rating": 4.8,
        "reviews_count": 63,
        "badge": "MCI/NMC Certified",
        "bio": "A psychiatrist for clients who need diagnostic clarity, medication conversations, and collaborative planning alongside therapy.",
        "license_info": "MD Psychiatry, MCI Registration No. MCI/12-45678",
        "qualifications": ["MBBS (AIIMS)", "MD Psychiatry", "International Member APA"],
        "approaches": ["Psychiatric evaluation", "Medication management", "Psychoeducation"],
        "focus_areas": ["Depression", "Complex anxiety", "Sleep issues", "Medication review"],
        "best_for": "Adults considering psychiatric support and wanting a clear explanation of options, risks, and follow-up steps.",
        "first_session": "The first visit reviews symptoms, treatment history, risk factors, and whether medication, therapy, or both make sense.",
        "cancellation_policy": "Psychiatric appointments require 24-hour notice for rescheduling due to high demand.",
        "review_summary": "Clients value Ankur's calm explanations and direct guidance when symptoms feel confusing or severe.",
        "availability": ["Mon 5 PM", "Wed 3 PM", "Fri 10 AM"],
        "photo_url": "",
        "profile_source": "managed",
    },
    {
        "id": 4,
        "name": "Aanchal Patel",
        "initials": "AP",
        "email": "aanchal@moodmate.in",
        "password_hash": "pbkdf2:sha256:600000$ByUQYNv9I7Ggm37g$249b1539ee80f2a94d0ca027ede270e250eefc62e92645a0916542e39acc8d92",
        "specialization": "Art Therapy",
        "experience_years": 4,
        "languages": ["Hindi"],
        "modes": ["Video", "Chat"],
        "price_per_session": 499,
        "rating": 4.6,
        "reviews_count": 39,
        "badge": "Expressive therapy",
        "bio": "Uses visual reflection, gentle prompts, and creative exercises to help clients explore emotion when words are hard to find.",
        "license_info": "Art therapy sample profile for design and workflow demo",
        "qualifications": ["MA Psychology", "Expressive arts therapy training"],
        "approaches": ["Art therapy", "Narrative techniques", "Trauma-informed pacing"],
        "focus_areas": ["Emotional expression", "Grief", "Stress", "Identity", "Healing after conflict"],
        "best_for": "People who process visually, feel blocked in talk therapy, or want a softer entry into emotional work.",
        "first_session": "The first session focuses on comfort, emotional goals, and one simple expressive exercise that does not require art skill.",
        "cancellation_policy": "Sample policy: sessions can be moved up to 12 hours ahead when slots permit.",
        "review_summary": "Clients describe Aanchal as grounding and creative, especially when emotions feel difficult to name.",
        "availability": ["Wed 1 PM", "Fri 11 AM", "Sun 2 PM"],
        "photo_url": "",
        "profile_source": "sample",
    },
    {
        "id": 5,
        "name": "Aakash Patel",
        "initials": "AaP",
        "email": "aakash@moodmate.in",
        "password_hash": "pbkdf2:sha256:600000$jIU4OLBAUOkeTxoq$766635606a6e7d0dcfde07c758017f363fdc54544d180e1515c91bd09f137082",
        "specialization": "Cognitive Behavioral Therapy",
        "experience_years": 10,
        "languages": ["Hindi", "English", "Gujarati"],
        "modes": ["Video", "Chat"],
        "price_per_session": 899,
        "rating": 4.9,
        "reviews_count": 142,
        "badge": "Most experienced sample",
        "bio": "Helps clients understand thought loops, behavior patterns, and the daily habits that keep anxiety and low mood running.",
        "license_info": "CBT-focused therapist sample profile for demo workflows",
        "qualifications": ["MSc Applied Psychology", "Advanced CBT certification"],
        "approaches": ["CBT", "Behavioral activation", "Habit design"],
        "focus_areas": ["Anxiety", "Overthinking", "Low mood", "Avoidance", "Performance stress"],
        "best_for": "Clients who want structure, worksheets, and a therapist who translates insight into action.",
        "first_session": "The first meeting identifies one primary pattern to work on and ends with a practical exercise for the coming week.",
        "cancellation_policy": "Sample policy: same-day cancellations are not guaranteed for refund or transfer.",
        "review_summary": "Clients say Aakash is especially useful when they want therapy to feel concrete, trackable, and skill-based.",
        "availability": ["Mon 11 AM", "Tue 4 PM", "Thu 6 PM"],
        "photo_url": "",
        "profile_source": "sample",
    },
    {
        "id": 6,
        "name": "Nitin Kumar",
        "initials": "NK",
        "email": "nitin@moodmate.in",
        "password_hash": "pbkdf2:sha256:600000$WsoSHoVg4SAXhLvJ$b44eb276311a5c3f1eb46314cc68a4589f04afafe910bbf7f98404d76e9eb92f",
        "specialization": "Mindfulness and Stress Recovery",
        "experience_years": 6,
        "languages": ["English", "Hindi"],
        "modes": ["Video", "Voice"],
        "price_per_session": 649,
        "rating": 4.7,
        "reviews_count": 58,
        "badge": "Mindfulness-led support",
        "bio": "Focuses on body-based grounding, mindfulness routines, and nervous-system-friendly recovery for busy people under constant pressure.",
        "license_info": "Mindfulness coach sample profile for preview use",
        "qualifications": ["MA Psychology", "Mindfulness teacher training"],
        "approaches": ["Mindfulness", "Breathwork", "Stress recovery planning"],
        "focus_areas": ["Stress", "Sleep", "Burnout", "Emotional regulation"],
        "best_for": "People who want steady support, calming practices, and better daily recovery habits rather than intensive analysis.",
        "first_session": "The first session explores stress triggers, body signals, and one realistic regulation routine to start immediately.",
        "cancellation_policy": "Sample policy: please reschedule at least 12 hours in advance when possible.",
        "review_summary": "Clients appreciate Nitin's calmer pace and practical recovery tools when life feels constantly switched on.",
        "availability": ["Tue 8 AM", "Sat 10 AM", "Sun 5 PM"],
        "photo_url": "",
        "profile_source": "sample",
    },
]
